### ISSUE TITLE
[Enhancement request] Reset token facing

### ISSUE THREAD

**Issue by confucianscholar** [jessev14/Reset-Movement#1]
When the token resets, one of two behaviours can be seen, both of which are undesirable:

1. If any modules are installed which adjust token facing automatically based on movement (e.g. face token up when the player moves up), then the reset button will also adjust the facing based on the path taken from the current location to the reset location. For example, tokenA starts the combat round facing downward. Player moves the token up 3 spaces and right 3 spaces. GM hits the reset button, and the token takes a direct path to it's original spot, moving down-left diagonally 3 spaces, and resets position, but is now facing down-right.

2. If no modules are installed which auto-adjust faces (i.e. vanilla Foundry behaviour), but the player changes the facing manually during their movement, upon resetting, the changed facing remains after the position resets.

In both cases, it would be ideal if the facing state was remembered along with the position state and applied upon reset.

**Comment by jessev14** [comment]
Good point; will save token rotation as well as position and reset both.
