### ISSUE TITLE
[Request] Integration with Drag Ruler - Reset Movement History

### ISSUE THREAD

**Issue by CurtR95** [jessev14/Reset-Movement#3]
It would be nice to have if this also fired a reset movement history request to Drag Ruler as part of the request. Should be a case of checking the module is installed and then calling a reset with this API call: dragRuler.resetMovementHistory(combat, combatantId);

Happy to raise a pull request if you want me to, but thought it was a fairly simple idea.

**Comment by jessev14** [comment]
Good idea. I use Drag Ruler but not the movement history feature, so I didn't think of this. Should be a straightforward integration. Will put out an update later today.

**Comment by jessev14** [comment]
Implemented in v1.3.6.
