### ISSUE TITLE
[Bug] Player client tries to update dm tokens, gets error message

### ISSUE THREAD

**Issue by inwerno** [jessev14/Reset-Movement#5]
Hi, I just wanted to leave a note:

When the module is configured to allow reset for players, and the initiative switches to an NPC token (where the player doesn't have the rights), it will produce an error message (User xxx lacks permission to update token yyy).

I suppose this can be fixed within resetMovement.js by checking for currentToken._canUpdate() around line 31 or something like that.

tested on Foundry v9 build 249, Game System DnD5e 1.5.7

**Comment by jessev14** [comment]
try updating to version 1.5.1 and see if that fixes it

**Comment by inwerno** [comment]
Seems fixed from my testing, thank you!
